### ISSUE TITLE
Metabox CSS issues overview

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#43]
- [x] Fix font color https://github.com/Yoast/gutenberg/issues/35
- [x] Fix input field heights https://github.com/Yoast/gutenberg/issues/36
- [x] Remove rounded corners from input fields https://github.com/Yoast/gutenberg/issues/37
- [x] Metabox width is restricted to 636px https://github.com/Yoast/gutenberg/issues/38
- [x] Fix social tab premium upsell alignment https://github.com/Yoast/gutenberg/issues/39
- [x] Radio buttons are not circular https://github.com/Yoast/gutenberg/issues/40
- [x] Fix input field padding https://github.com/Yoast/gutenberg/issues/41
- [x] Fix input field focus style https://github.com/Yoast/gutenberg/issues/42
- [x] Fix colors of analysis bullets https://github.com/Yoast/gutenberg/issues/24
- [x] Fix premium keyword close button icon https://github.com/Yoast/gutenberg/issues/28
- [x] Fix coloring of the need help icons https://github.com/Yoast/gutenberg/issues/29
- [x] Remove grey dots in content analysis https://github.com/Yoast/gutenberg/issues/25
- [x] Fix cornerstone checkbox styling https://github.com/Yoast/gutenberg/issues/27
